-- MySQL Script generated by MySQL Workbench
-- jue 10 dic 2020 13:37:37
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Libronline
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Libronline
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Libronline` ;
USE `Libronline` ;

-- -----------------------------------------------------
-- Table `Libronline`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libronline`.`usuarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombreUsuario` VARCHAR(45) NULL,
  `correo` VARCHAR(45) NULL,
  `contrasena` VARCHAR(45) NULL,
  `tipoCuenta` ENUM("Admin", "Editor", "Lector") NULL,
  `deleted_at` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libronline`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libronline`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NULL,
  `descripcion` VARCHAR(300) NULL,
  `cantidadArticulos` INT NULL,
  `deleted_at` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libronline`.`articulos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libronline`.`articulos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `urlArticulo` VARCHAR(45) NULL,
  `titulo` VARCHAR(50) NULL,
  `autor` INT NULL,
  `fechaPublicacion` DATETIME NULL,
  `categoria` INT NULL,
  `contenido` VARCHAR(2500) NULL,
  `cantidadComentarios` INT NULL,
  `fueEditado` TINYINT NULL,
  `fechaEdicion` DATETIME NULL,
  `deleted_at` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_articulos_autor`
    FOREIGN KEY (`autor`)
    REFERENCES `Libronline`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulos_categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `Libronline`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Libronline`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Libronline`.`comentarios` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATETIME NULL,
  `autor` INT NULL,
  `articulo` INT NULL,
  `comentario` VARCHAR(1500) NULL,
  `fueEditado` TINYINT NULL,
  `fechaEdicion` DATETIME NULL,
  `deleted_at` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `fk_autor`
    FOREIGN KEY (`autor`)
    REFERENCES `Libronline`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_articulo`
    FOREIGN KEY (`articulo`)
    REFERENCES `Libronline`.`articulos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

USE Libronline;

INSERT INTO categorias VALUES (NULL, 'Matemáticas', 'Categoría que incluye cualquier información de tipo de cálculo matemático o numérico', 0, NULL);
INSERT INTO categorias VALUES (NULL, 'Lenguaje', 'Información acerca de conceptos lingüísticos sin importar el idioma en el que estén', 0, NULL);
INSERT INTO categorias VALUES (NULL, 'Historia', 'Artículos con fijación en eventos previos y que contienen información acerca de ellos', 0, NULL);
INSERT INTO categorias VALUES (NULL, 'Otros', 'Aquí es donde van los demás artículos cuyo contenido no encaja en otro lugar', 0, NULL);

INSERT INTO usuarios VALUES (NULL, 'admin', 'admin@libronline.com', 'pastrami55', 'Admin', NULL);
INSERT INTO usuarios VALUES (NULL, 'Ubaldo', 'ubaldo@mail.com', 'ubaldo96ix9ine69', 'Editor', NULL);
INSERT INTO usuarios VALUES (NULL, 'Victor', 'victor@mail.com', 'laguanteratienemanos', 'Lector', NULL);

INSERT INTO articulos VALUES (NULL, 'Vaporeon', 'Información acerca de Vaporeon', 1, '2020-12-01 01:00:00', 4, '<p>
                    Lorem, ipsum dolor sit amet consectetur adipisicing elit. Laudantium repellendus doloribus, optio
                    qui aliquam nobis necessitatibus, eligendi atque reiciendis ex ratione, magnam in vero impedit non
                    earum! Quibusdam, suscipit illo!
                    Lorem ipsum dolor sit amet consectetur, adipisicing elit. Dolor sapiente molestias autem nemo
                    nesciunt nam asperiores enim dolorem a aliquid, suscipit facilis. Suscipit velit aliquid, facere
                    quis beatae eveniet ad.
                    Lorem ipsum dolor sit amet consectetur adipisicing elit. Eum provident mollitia autem quaerat
                    facilis, error iure voluptates doloribus commodi recusandae exercitationem dolorum, enim in. Ipsam
                    tempora temporibus recusandae molestias officiis?
                </p>
                <div class="imgContainer text-center d-block mb-2">
                    <img src="<?php echo base_url(); ?>/assets/img/vaporeon.png" alt="Vaporeon">
                </div>', 1, FALSE, '2020-12-01 01:00:00', NULL);

INSERT INTO comentarios VALUES (NULL, '2020-12-01 00:00:00', 1, 1, 'Este es un comentario de prueba. <h1>Hola Mundo!</h1>', FALSE, '2020-12-01 00:00:00', NULL);
INSERT INTO comentarios VALUES (NULL, '2020-12-02 00:00:00', 1, 1, 'PERIDOT <h1>PERIDOT</h1>', FALSE, '2020-12-02 00:00:00', NULL);
